Traceback (most recent call last):
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Hp\anaconda3\envs\MACHINE\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Iniciar sesiÃ³n Spark
spark = SparkSession.builder \
    .appName("MyMini") \
    .getOrCreate()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[5], line 4[0m
[0;32m      1[0m [38;5;66;03m# Iniciar sesiÃ³n Spark[39;00m
[0;32m      2[0m spark [38;5;241m=[39m [43mSparkSession[49m[38;5;241;43m.[39;49m[43mbuilder[49m[43m [49m[43m\[49m
[0;32m      3[0m [43m    [49m[38;5;241;43m.[39;49m[43mappName[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mMyMini[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m [49m[43m\[49m
[1;32m----> 4[0m [43m    [49m[38;5;241;43m.[39;49m[43mgetOrCreate[49m[43m([49m[43m)[49m

File [1;32m~\anaconda3\envs\MACHINE\lib\site-packages\pyspark\sql\session.py:556[0m, in [0;36mSparkSession.Builder.getOrCreate[1;34m(self)[0m
[0;32m    554[0m     sparkConf[38;5;241m.[39mset(key, value)
[0;32m    555[0m [38;5;66;03m# This SparkContext may be an existing one.[39;00m
[1;32m--> 556[0m sc [38;5;241m=[39m [43mSparkContext[49m[38;5;241;43m.[39;49m[43mgetOrCreate[49m[43m([49m[43msparkConf[49m[43m)[49m
[0;32m    557[0m [38;5;66;03m# Do not update `SparkConf` for existing `SparkContext`, as it's shared[39;00m
[0;32m    558[0m [38;5;66;03m# by all sessions.[39;00m
[0;32m    559[0m session [38;5;241m=[39m SparkSession(sc, options[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_options)

File [1;32m~\anaconda3\envs\MACHINE\lib\site-packages\pyspark\core\context.py:523[0m, in [0;36mSparkContext.getOrCreate[1;34m(cls, conf)[0m
[0;32m    521[0m [38;5;28;01mwith[39;00m SparkContext[38;5;241m.[39m_lock:
[0;32m    522[0m     [38;5;28;01mif[39;00m SparkContext[38;5;241m.[39m_active_spark_context [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m--> 523[0m         [43mSparkContext[49m[43m([49m[43mconf[49m[38;5;241;43m=[39;49m[43mconf[49m[43m [49m[38;5;129;43;01mor[39;49;00m[43m [49m[43mSparkConf[49m[43m([49m[43m)[49m[43m)[49m
[0;32m    524[0m     [38;5;28;01massert[39;00m SparkContext[38;5;241m.[39m_active_spark_context [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m    525[0m     [38;5;28;01mreturn[39;00m SparkContext[38;5;241m.[39m_active_spark_context

File [1;32m~\anaconda3\envs\MACHINE\lib\site-packages\pyspark\core\context.py:205[0m, in [0;36mSparkContext.__init__[1;34m(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)[0m
[0;32m    199[0m [38;5;28;01mif[39;00m gateway [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m gateway[38;5;241m.[39mgateway_parameters[38;5;241m.[39mauth_token [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m    200[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    201[0m         [38;5;124m"[39m[38;5;124mYou are trying to pass an insecure Py4j gateway to Spark. This[39m[38;5;124m"[39m
[0;32m    202[0m         [38;5;124m"[39m[38;5;124m is not allowed as it is a security risk.[39m[38;5;124m"[39m
[0;32m    203[0m     )
[1;32m--> 205[0m [43mSparkContext[49m[38;5;241;43m.[39;49m[43m_ensure_initialized[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mgateway[49m[38;5;241;43m=[39;49m[43mgateway[49m[43m,[49m[43m [49m[43mconf[49m[38;5;241;43m=[39;49m[43mconf[49m[43m)[49m
[0;32m    206[0m [38;5;28;01mtry[39;00m:
[0;32m    207[0m     [38;5;28mself[39m[38;5;241m.[39m_do_init(
[0;32m    208[0m         master,
[0;32m    209[0m         appName,
[1;32m   (...)[0m
[0;32m    219[0m         memory_profiler_cls,
[0;32m    220[0m     )

File [1;32m~\anaconda3\envs\MACHINE\lib\site-packages\pyspark\core\context.py:444[0m, in [0;36mSparkContext._ensure_initialized[1;34m(cls, instance, gateway, conf)[0m
[0;32m    442[0m [38;5;28;01mwith[39;00m SparkContext[38;5;241m.[39m_lock:
[0;32m    443[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m SparkContext[38;5;241m.[39m_gateway:
[1;32m--> 444[0m         SparkContext[38;5;241m.[39m_gateway [38;5;241m=[39m gateway [38;5;129;01mor[39;00m [43mlaunch_gateway[49m[43m([49m[43mconf[49m[43m)[49m
[0;32m    445[0m         SparkContext[38;5;241m.[39m_jvm [38;5;241m=[39m SparkContext[38;5;241m.[39m_gateway[38;5;241m.[39mjvm
[0;32m    447[0m     [38;5;28;01mif[39;00m instance:

File [1;32m~\anaconda3\envs\MACHINE\lib\site-packages\pyspark\java_gateway.py:104[0m, in [0;36mlaunch_gateway[1;34m(conf, popen_kwargs)[0m
[0;32m    101[0m     proc [38;5;241m=[39m Popen(command, [38;5;241m*[39m[38;5;241m*[39mpopen_kwargs)
[0;32m    102[0m [38;5;28;01melse[39;00m:
[0;32m    103[0m     [38;5;66;03m# preexec_fn not supported on Windows[39;00m
[1;32m--> 104[0m     proc [38;5;241m=[39m Popen(command, [38;5;241m*[39m[38;5;241m*[39mpopen_kwargs)
[0;32m    106[0m [38;5;66;03m# Wait for the file to appear, or for the process to exit, whichever happens first.[39;00m
[0;32m    107[0m [38;5;28;01mwhile[39;00m [38;5;129;01mnot[39;00m proc[38;5;241m.[39mpoll() [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39misfile(conn_info_file):

File [1;32m~\anaconda3\envs\MACHINE\lib\subprocess.py:971[0m, in [0;36mPopen.__init__[1;34m(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize)[0m
[0;32m    967[0m         [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mtext_mode:
[0;32m    968[0m             [38;5;28mself[39m[38;5;241m.[39mstderr [38;5;241m=[39m io[38;5;241m.[39mTextIOWrapper([38;5;28mself[39m[38;5;241m.[39mstderr,
[0;32m    969[0m                     encoding[38;5;241m=[39mencoding, errors[38;5;241m=[39merrors)
[1;32m--> 971[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_execute_child[49m[43m([49m[43margs[49m[43m,[49m[43m [49m[43mexecutable[49m[43m,[49m[43m [49m[43mpreexec_fn[49m[43m,[49m[43m [49m[43mclose_fds[49m[43m,[49m
[0;32m    972[0m [43m                        [49m[43mpass_fds[49m[43m,[49m[43m [49m[43mcwd[49m[43m,[49m[43m [49m[43menv[49m[43m,[49m
[0;32m    973[0m [43m                        [49m[43mstartupinfo[49m[43m,[49m[43m [49m[43mcreationflags[49m[43m,[49m[43m [49m[43mshell[49m[43m,[49m
[0;32m    974[0m [43m                        [49m[43mp2cread[49m[43m,[49m[43m [49m[43mp2cwrite[49m[43m,[49m
[0;32m    975[0m [43m                        [49m[43mc2pread[49m[43m,[49m[43m [49m[43mc2pwrite[49m[43m,[49m
[0;32m    976[0m [43m                        [49m[43merrread[49m[43m,[49m[43m [49m[43merrwrite[49m[43m,[49m
[0;32m    977[0m [43m                        [49m[43mrestore_signals[49m[43m,[49m
[0;32m    978[0m [43m                        [49m[43mgid[49m[43m,[49m[43m [49m[43mgids[49m[43m,[49m[43m [49m[43muid[49m[43m,[49m[43m [49m[43mumask[49m[43m,[49m
[0;32m    979[0m [43m                        [49m[43mstart_new_session[49m[43m)[49m
[0;32m    980[0m [38;5;28;01mexcept[39;00m:
[0;32m    981[0m     [38;5;66;03m# Cleanup if the child failed starting.[39;00m
[0;32m    982[0m     [38;5;28;01mfor[39;00m f [38;5;129;01min[39;00m [38;5;28mfilter[39m([38;5;28;01mNone[39;00m, ([38;5;28mself[39m[38;5;241m.[39mstdin, [38;5;28mself[39m[38;5;241m.[39mstdout, [38;5;28mself[39m[38;5;241m.[39mstderr)):

File [1;32m~\anaconda3\envs\MACHINE\lib\subprocess.py:1456[0m, in [0;36mPopen._execute_child[1;34m(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)[0m
[0;32m   1454[0m [38;5;66;03m# Start the process[39;00m
[0;32m   1455[0m [38;5;28;01mtry[39;00m:
[1;32m-> 1456[0m     hp, ht, pid, tid [38;5;241m=[39m [43m_winapi[49m[38;5;241;43m.[39;49m[43mCreateProcess[49m[43m([49m[43mexecutable[49m[43m,[49m[43m [49m[43margs[49m[43m,[49m
[0;32m   1457[0m [43m                             [49m[38;5;66;43;03m# no special security[39;49;00m
[0;32m   1458[0m [43m                             [49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m,[49m
[0;32m   1459[0m [43m                             [49m[38;5;28;43mint[39;49m[43m([49m[38;5;129;43;01mnot[39;49;00m[43m [49m[43mclose_fds[49m[43m)[49m[43m,[49m
[0;32m   1460[0m [43m                             [49m[43mcreationflags[49m[43m,[49m
[0;32m   1461[0m [43m                             [49m[43menv[49m[43m,[49m
[0;32m   1462[0m [43m                             [49m[43mcwd[49m[43m,[49m
[0;32m   1463[0m [43m                             [49m[43mstartupinfo[49m[43m)[49m
[0;32m   1464[0m [38;5;28;01mfinally[39;00m:
[0;32m   1465[0m     [38;5;66;03m# Child is launched. Close the parent's copy of those pipe[39;00m
[0;32m   1466[0m     [38;5;66;03m# handles that only the child should have open.  You need[39;00m
[1;32m   (...)[0m
[0;32m   1469[0m     [38;5;66;03m# pipe will not close when the child process exits and the[39;00m
[0;32m   1470[0m     [38;5;66;03m# ReadFile will hang.[39;00m
[0;32m   1471[0m     [38;5;28mself[39m[38;5;241m.[39m_close_pipe_fds(p2cread, p2cwrite,
[0;32m   1472[0m                          c2pread, c2pwrite,
[0;32m   1473[0m                          errread, errwrite)

[1;31mFileNotFoundError[0m: [WinError 2] El sistema no puede encontrar el archivo especificado

